### ISSUE TITLE
Invalid Token Error: cryptography.fernet.InvalidToken

### ISSUE THREAD

**Issue by TianaCo** [willylulu/celeba-hq-modified#2]
Traceback (most recent call last):
  File "h5tool.py", line 706, in <module>
    execute_cmdline(sys.argv)
  File "h5tool.py", line 701, in execute_cmdline
    func(**vars(args))
  File "h5tool.py", line 607, in create_celeba_hq
    aidx, aimg64, aimg128, aimg256, aimg512, aimg1024 = process_func(x)
  File "h5tool.py", line 582, in process_func
    delta = np.frombuffer(bz2.decompress(cryptography.fernet.Fernet(key).decrypt(delta_bytes)), dtype=np.uint8).reshape(3, 1024, 1024)
  File "/home/ubuntu/miniconda3/envs/CelebAHQ2/lib/python2.7/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/home/ubuntu/miniconda3/envs/CelebAHQ2/lib/python2.7/site-packages/cryptography/fernet.py", line 119, in _decrypt_data
    self._verify_signature(data)
  File "/home/ubuntu/miniconda3/envs/CelebAHQ2/lib/python2.7/site-packages/cryptography/fernet.py", line 108, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken

**Comment by Mintpcc** [comment]
you can add a line like this: "salt = bytes(origis_file, 'ascii')" before salt used.

**Comment by Mintpcc** [comment]
> Traceback (most recent call last):
> File "h5tool.py", line 706, in 
> execute_cmdline(sys.argv)
> File "h5tool.py", line 701, in execute_cmdline
> func(**vars(args))
> File "h5tool.py", line 607, in create_celeba_hq
> aidx, aimg64, aimg128, aimg256, aimg512, aimg1024 = process_func(x)
> File "h5tool.py", line 582, in process_func
> delta = np.frombuffer(bz2.decompress(cryptography.fernet.Fernet(key).decrypt(delta_bytes)), dtype=np.uint8).reshape(3, 1024, 1024)
> File "/home/ubuntu/miniconda3/envs/CelebAHQ2/lib/python2.7/site-packages/cryptography/fernet.py", line 75, in decrypt
> return self._decrypt_data(data, timestamp, ttl)
> File "/home/ubuntu/miniconda3/envs/CelebAHQ2/lib/python2.7/site-packages/cryptography/fernet.py", line 119, in _decrypt_data
> self._verify_signature(data)
> File "/home/ubuntu/miniconda3/envs/CelebAHQ2/lib/python2.7/site-packages/cryptography/fernet.py", line 108, in _verify_signature
> raise InvalidToken
> cryptography.fernet.InvalidToken

you can add a line like this: "salt = bytes(origis_file, 'ascii')" before salt used.

**Comment by willylulu** [comment]
Thank you for your help :)

**Comment by SungjinChoi1128** [comment]
> File "h5tool.py", line 607, in create_celeba_hq

I have the same error and added a line
salt = bytes(orig_file.encode('ascii'))
kdf = cryptography.hazmat.primitives.kdf.pbkdf2.PBKDF2HMAC(algorithm=algorithm, length=32, salt= salt, iterations=100000, backend=backend)

and still got the same error any idea how to solve this error? I use python 2.7.15
